### ISSUE TITLE
如何使用它呢？

### ISSUE THREAD

**Issue by Hwzsnow** [athlonreg/ASRock-Z370-Pro4-Hackintosh#1]
您好，请问对于新手而言如何使用它呢？ 从零开始安装的步骤或者教学可以提供下吗？万分感谢，因为我是根据您的配置购买的配件

**Comment by athlonreg** [comment]
> 您好，请问对于新手而言如何使用它呢？ 从零开始安装的步骤或者教学可以提供下吗？万分感谢，因为我是根据您的配置购买的配件

https://blog.cloudops.ml/Install-macOS-on-laptop.html
